#
#    SfynxAuthBundle routing url
#
auth_user_security:
    resource: "@SfynxAuthBundle/Resources/config/routing/security.xml"

auth_user_resetting:
    resource: "@SfynxAuthBundle/Resources/config/routing/resetting.xml"
    prefix: /user/resetting

auth_user_profile:
    resource: "@SfynxAuthBundle/Resources/config/routing/profile.xml"
    prefix: /user/profile

auth_users:
    resource: "@SfynxAuthBundle/Resources/config/routing/users.xml"
    prefix: /admin/users

unauthorized:
    path:  /unauthorized
    defaults: { _controller: SfynxAuthBundle:Error:unauthorized }

auth_public:
    resource: "@SfynxAuthBundle/Resources/config/routing/public.xml"
    prefix: /

auth_langue:
    resource: "@SfynxAuthBundle/Resources/config/routing/langue.xml"
    prefix: /admin/langue

auth_layout:
    resource: "@SfynxAuthBundle/Resources/config/routing/layout.xml"
    prefix: /admin/layout
