parameters:
    # Manager class
    sfynx.auth.manager.group.entity.class: Sfynx\AuthBundle\Domain\Service\Group\Manager\EntityManager
    sfynx.auth.manager.group.params:
        class: '%sfynx.auth.mapping.group.class%'
    # Adapter factory class
    sfynx.auth.factory.group.class: Sfynx\CoreBundle\Layers\Infrastructure\Persistence\Factory\MultiAdapterFactory

    # ORM QueryBuilder names
    sfynx.auth.repository.group.orm.query.querybuilder: []
    sfynx.auth.repository.group.orm.command.querybuilder: []
    # COUCHDB QueryBuilder names
    sfynx.auth.repository.group.couchdb.query.querybuilder: []
    sfynx.auth.repository.group.couchdb.command.querybuilder: []

services:
    #
    # configuration of the user manager working with Orm, Odm, Couchdb
    #
    sfynx.auth.manager.group.entity:
        class: '%sfynx.auth.manager.group.entity.class%'
        arguments:
            - '@sfynx.auth.factory.group'
            - '@security.encoder_factory'
            - '@sfynx.core.request.strategy'
            - '@security.token_storage'
            - '@service_container'
        calls:
            - [ setParams, [ '%sfynx.auth.manager.group.params%' ] ]
