parameters:
    # Manager class
    sfynx.auth.manager.langue.entity.class: Sfynx\AuthBundle\Domain\Service\Langue\Manager\EntityManager
    sfynx.auth.manager.langue.params:
        class: '%sfynx.auth.mapping.langue.class%'
    # Adapter factory class
    sfynx.auth.factory.langue.class: Sfynx\CoreBundle\Layers\Infrastructure\Persistence\Factory\MultiAdapterFactory

    # ORM QueryBuilder names
    sfynx.auth.repository.langue.orm.query.querybuilder: []
    sfynx.auth.repository.langue.orm.command.querybuilder: []
    # COUCHDB QueryBuilder names
    sfynx.auth.repository.langue.couchdb.query.querybuilder: []
    sfynx.auth.repository.langue.couchdb.command.querybuilder: []

services:
    #
    # configuration of the user manager working with Orm, Odm, Couchdb
    #
    sfynx.auth.manager.langue.entity:
        class: '%sfynx.auth.manager.langue.entity.class%'
        arguments:
            - '@sfynx.auth.factory.langue'
            - '@security.encoder_factory'
            - '@sfynx.core.request.strategy'
            - '@security.token_storage'
            - '@service_container'
        calls:
            - [ setParams, [ '%sfynx.auth.manager.langue.params%' ] ]
