parameters:
    # Manager class
    sfynx.auth.manager.layout.entity.class: Sfynx\AuthBundle\Domain\Service\Layout\Manager\EntityManager
    # Adapter factory class
    sfynx.auth.factory.layout.class: Sfynx\CoreBundle\Layers\Infrastructure\Persistence\Factory\MultiAdapterFactory
    # Entity class value
    sfynx.auth.manager.layout.params:
      class: '%sfynx.auth.user_class%'
    # Reposioty names
    sfynx.auth.repository.layout.orm.command.class: Sfynx\AuthBundle\Infrastructure\Persistence\Adapter\Command\Orm\LayoutRepository
    sfynx.auth.repository.layout.orm.query.class: Sfynx\AuthBundle\Infrastructure\Persistence\Adapter\Query\Orm\LayoutRepository

services:
    #
    # configuration of the user manager working with Orm, Odm, Couchdb
    #
    sfynx.auth.manager.layout.entity:
        class: '%sfynx.auth.manager.layout.entity.class%'
        arguments:
            - '@sfynx.auth.factory.layout'
            - '@security.encoder_factory'
            - '@sfynx.core.request.strategy'
            - '@security.token_storage'
            - '@service_container'
        calls:
            - [ setParams, [ '%sfynx.auth.manager.layout.params%' ] ]
