parameters:
    # Manager class
    sfynx.auth.manager.role.entity.class: Sfynx\AuthBundle\Domain\Service\Role\Manager\EntityManager
    # Adapter factory class
    sfynx.auth.factory.role.class: Sfynx\CoreBundle\Layers\Infrastructure\Persistence\Factory\MultiAdapterFactory
    # Entity class value
    sfynx.auth.manager.role.params:
      class: '%sfynx.auth.user_class%'
    # Reposioty names
    sfynx.auth.repository.role.orm.command.class: Sfynx\AuthBundle\Infrastructure\Persistence\Adapter\Command\Orm\RoleRepository
    sfynx.auth.repository.role.orm.query.class: Sfynx\AuthBundle\Infrastructure\Persistence\Adapter\Query\Orm\RoleRepository

services:
    #
    # configuration of the user manager working with Orm, Odm, Couchdb
    #
    sfynx.auth.manager.role.entity:
        class: '%sfynx.auth.manager.role.entity.class%'
        arguments:
            - '@sfynx.auth.factory.role'
            - '@security.encoder_factory'
            - '@sfynx.core.request.strategy'
            - '@security.token_storage'
            - '@service_container'
        calls:
            - [ setParams, [ '%sfynx.auth.manager.role.params%' ] ]
