parameters:
    # Manager class
    sfynx.auth.manager.user.entity.class: Sfynx\AuthBundle\Domain\Service\User\Manager\EntityManager
    sfynx.auth.manager.user.params:
        class: '%sfynx.auth.mapping.user.class%'
        firewall_name: '%sfynx.auth.firewall_name%'
        date_expire: '%sfynx.core.cookies.date_expire%'
        date_interval: '%sfynx.core.cookies.date_interval%'
    # Adapter factory class
    sfynx.auth.factory.user.class: Sfynx\CoreBundle\Layers\Infrastructure\Persistence\Factory\MultiAdapterFactory

    # ORM QueryBuilder names
    sfynx.auth.repository.user.orm.query.querybuilder: []
    sfynx.auth.repository.user.orm.command.querybuilder: []
    # COUCHDB QueryBuilder names
    sfynx.auth.repository.user.couchdb.query.querybuilder: []
    sfynx.auth.repository.user.couchdb.command.querybuilder: []

services:
    #
    # configuration of the user manager working with Orm, Odm, Couchdb
    #
    sfynx.auth.manager.user.entity:
        class: '%sfynx.auth.manager.user.entity.class%'
        arguments:
            - '@sfynx.auth.factory.user'
            - '@security.encoder_factory'
            - '@sfynx.core.request.strategy'
            - '@security.token_storage'
            - '@service_container'
        calls:
            - [ setParams, [ '%sfynx.auth.manager.user.params%' ] ]
