Sfynx\AuthBundle\Domain\EntityVO\Ressource:
    type: entity
    table: Fos_ressource
    id:
        id:
            type: integer
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
            id: true
            column: ID
            generator:
                strategy: IDENTITY
    fields:
        ressource.routeName:
            type: string
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
            originalClass: Sfynx\AuthBundle\Domain\ValueObject\RessourceVO
            declaredField: ressource
            originalField: routeName
            column: route_name
        ressource.slug:
            type: string
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
            originalClass: Sfynx\AuthBundle\Domain\ValueObject\RessourceVO
            declaredField: ressource
            originalField: slug
            column: slug
        ressource.url:
            type: string
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
            originalClass: Sfynx\AuthBundle\Domain\ValueObject\RessourceVO
            declaredField: ressource
            originalField: url
            column: url
        ressource.createdAt:
            type: datetime
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
            originalClass: Sfynx\AuthBundle\Domain\ValueObject\RessourceVO
            declaredField: ressource
            originalField: createdAt
            column: created_at
        ressource.updatedAt:
            type: datetime
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
            originalClass: Sfynx\AuthBundle\Domain\ValueObject\RessourceVO
            declaredField: ressource
            originalField: updatedAt
            column: updated_at
        ressource.publishedAt:
            type: datetime
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
            originalClass: Sfynx\AuthBundle\Domain\ValueObject\RessourceVO
            declaredField: ressource
            originalField: publishedAt
            column: published_at
        ressource.archiveAt:
            type: datetime
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
            originalClass: Sfynx\AuthBundle\Domain\ValueObject\RessourceVO
            declaredField: ressource
            originalField: archiveAt
            column: archive_at
        ressource.archived:
            type: boolean
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
            originalClass: Sfynx\AuthBundle\Domain\ValueObject\RessourceVO
            declaredField: ressource
            originalField: archived
            column: archived
        ressource.enabled:
            type: boolean
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
            originalClass: Sfynx\AuthBundle\Domain\ValueObject\RessourceVO
            declaredField: ressource
            originalField: enabled
            column: enabled
    lifecycleCallbacks: {  }
